name: Push to AWS S3
run-name: ${{ github.actor }} is running this GitHub Actions pipeline 🚀

on:
  push:
    branches:
      - main

jobs:
  push-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you need

      - name: Run npm install
        run: npm install --legacy-peer-deps

      - name: Fix permissions
        run: chmod -R +x node_modules/.bin

      - name: Update Browserslist database
        run: npx update-browserslist-db@latest

      - name: Run npm build
        run: |
          CI=false npm run build

      - name: List the directories
        run: ls

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: build/
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
